import type { Metadata } from 'next';
import { Roboto_Mono } from 'next/font/google';
import './globals.css';
import Header from '../components/Header';
import StoreProvider from './StoreProvider';
import { NextUIProvider } from '@nextui-org/react';
import { UIProviders } from './providers';

const roboto_Mono = Roboto_Mono({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto_Mono.className}>
        <StoreProvider>
          <Header />
          <div className="container mx-auto">{children}</div>
        </StoreProvider>
      </body>
    </html>
  );
}
